<?php
defined( 'ABSPATH' ) || exit;

class EcomSurance_Admin {
	const NONCE = 'akismet-update-key';

    private static $initiated = false;

    public static function init() {
		if ( ! self::$initiated ) {
			self::init_hooks();
		}
	}

    public static function init_hooks() {
		// The standalone stats page was removed in 3.0 for an all-in-one config and stats page.
		// Redirect any links that might have been bookmarked or in browser history.
		if ( isset( $_GET['page'] ) && 'ecomsurance-stats-display' == sanitize_text_field($_GET['page']) ) {
			wp_safe_redirect( esc_url_raw( self::get_page_url( 'stats' ) ), 301 );
			die;
		}

		self::$initiated = true;

		add_action( 'admin_init', array( 'EcomSurance_Admin', 'admin_init' ) );
		$plugin_path = trailingslashit( WP_PLUGIN_DIR ) . 'woocommerce/woocommerce.php';

		if ( !in_array( $plugin_path, wp_get_active_and_valid_plugins()  )
		) { 
			function general_admin_notice(){
				 
				echo '<div class="notice notice-warning is-dismissible">
					<p>Ecomsurance plugin need woocommerce plugin active.</p>
				</div>';
				 
			}
			add_action('admin_notices', 'general_admin_notice');
			// wp_redirect( add_query_arg( array(),  admin_url( 'plugins.php' ) ) );
			// exit;
		}else{
			add_action( 'admin_menu', array( 'EcomSurance_Admin', 'admin_menu' ), 5 ); 
		}
    }

    public static function admin_init() {
		global $wpdb;
		
		$get_data = $wpdb->get_row(
			$wpdb->prepare(
				"SELECT * from ".$wpdb->prefix."posts WHERE post_name = %s", "order-claim"
			)
		);

		if(empty($get_data)){
			$post_arr_data = array(
				"post_title" => "Order Claim",
				"post_name" => "order-claim",
				"post_author" => get_current_user_id(),
				"post_content" => "Autogenerated Ecomsurance page for Claim Order",
				"post_type" => "page",
				"post_statu" => "publish",
				'post_date' => date('Y-m-d H:i:s')
			);
			$insertedpage = wp_insert_post($post_arr_data);
			$postupdate = array( 'ID' => $insertedpage, 'post_status' => "publish" );
			wp_update_post($postupdate);		
		}
		if ( get_option( 'Activated_EcomSurance' ) ) {
			delete_option( 'Activated_EcomSurance' );
			if ( ! headers_sent() ) {
				wp_redirect( add_query_arg( array( 'page' => 'ecomsurance'  ),  admin_url( 'admin.php' ) ) );
			}
		} 

		
	}

    public static function admin_menu() {
		add_menu_page("EcomSurance", "EcomSurance", "manage_options", "ecomsurance", array( 'EcomSurance_Admin', 'display_page' ), null, 99); 

		add_submenu_page("", "ecomsurance", "Billing", "manage_options", "ecomsurance-billing", array( 'EcomSurance_Admin', 'display_page_billing' ) );   

		add_submenu_page("", "ecomsurance", "Subscription", "manage_options", "ecomsurance-subscription", array( 'EcomSurance_Admin', 'display_page_subscription' ) );   

		add_submenu_page("", "ecomsurance", "Setting", "manage_options", "ecomsurance-setting", array( 'EcomSurance_Admin', 'display_page_setting' ));   

		add_submenu_page("", "ecomsurance", "Insurance Plan", "manage_options", "ecomsurance-insurance-plan", array( 'EcomSurance_Admin', 'display_page_insuranceplan' ));  

		add_submenu_page("", "ecomsurance", "Insurance Plan", "manage_options", "ecomsurance-insurance-plan-create", array( 'EcomSurance_Admin', 'display_page_insuranceplan_create' ));  

		add_submenu_page("", "ecomsurance", "Edit Popup", "manage_options", "ecomsurance-edit-popup", array( 'EcomSurance_Admin', 'display_page_edit_popup' ));  

		add_submenu_page("", "ecomsurance", "Inquiry", "manage_options", "ecomsurance-inquiry", array( 'EcomSurance_Admin', 'display_page_inquiry' ));  

		add_submenu_page("", "ecomsurance", "Orders", "manage_options", "ecomsurance-orders", array( 'EcomSurance_Admin', 'display_page_orders' )); 

		add_submenu_page("", "ecomsurance", "Orders Show", "manage_options", "ecomsurance-order-show", array( 'EcomSurance_Admin', 'display_page_order_show' )); 
		
		add_submenu_page("", "ecomsurance", "Claims", "manage_options", "ecomsurance-claims", array( 'EcomSurance_Admin', 'display_page_claims' ));  
		
		add_submenu_page("", "ecomsurance", "Email Templates", "manage_options", "ecomsurance-email-templates", array( 'EcomSurance_Admin', 'display_page_emailtemplates' )); 
		
		add_submenu_page("", "ecomsurance", "Email Templates Edit", "manage_options", "ecomsurance-email-templates-edit", array( 'EcomSurance_Admin', 'display_page_emailtemplatesedit' )); 
	}  
	
	public static function display_page() { 
		$response= EcomSurance_STRIPE::HasPaymentMethod(); 
		if($response == true){
			EcomSurance::view( 'dashboard' );
		}else{			
			EcomSurance::view( 'billing-portal' );
		}
	}

	public static function display_page_billing() { 
        EcomSurance::view( 'billing-portal' );
	}

	public static function display_page_subscription() { 
        EcomSurance::view( 'subscription' );
	}

	public static function display_page_setting() { 
		$response= EcomSurance_STRIPE::HasPaymentMethod(); 
		if($response == true){
			EcomSurance::view( 'setting' );
		}else{
			EcomSurance::view( 'billing-portal' );
		}
	}

	public static function display_page_insuranceplan() { 
		$response= EcomSurance_STRIPE::HasPaymentMethod(); 
		if($response == true){
			EcomSurance::view( 'insurance-plan' );
		}else{
			EcomSurance::view( 'billing-portal' );
		}
	}

	public static function display_page_insuranceplan_create() {
		$response= EcomSurance_STRIPE::HasPaymentMethod(); 
		if($response == true){
			EcomSurance::view( 'insurance-plan-create' );
		}else{
			EcomSurance::view( 'billing-portal' );
		} 
	}

	public static function display_page_edit_popup() { 
		$response= EcomSurance_STRIPE::HasPaymentMethod(); 
		if($response == true){
			EcomSurance::view( 'edit-popup' );
		}else{
			EcomSurance::view( 'billing-portal' );
		}
	}

	public static function display_page_inquiry() { 
		$response= EcomSurance_STRIPE::HasPaymentMethod(); 
		if($response == true){
			EcomSurance::view( 'inquiry' );
		}else{
			EcomSurance::view( 'billing-portal' );
		}
	}

	public static function display_page_orders() { 
		$response= EcomSurance_STRIPE::HasPaymentMethod(); 
		if($response == true){
			EcomSurance::view( 'orders' );
		}else{
			EcomSurance::view( 'billing-portal' );
		}
	}

	public static function display_page_order_show() { 
		$response= EcomSurance_STRIPE::HasPaymentMethod(); 
		if($response == true){
			EcomSurance::view( 'order-show' );
		}else{
			EcomSurance::view( 'billing-portal' );
		}
	} 

	public static function display_page_claims() { 
		$response= EcomSurance_STRIPE::HasPaymentMethod(); 
		if($response == true){
			EcomSurance::view( 'claims' );
		}else{
			EcomSurance::view( 'billing-portal' );
		}
	} 

	public static function display_page_emailtemplates() { 
		$response= EcomSurance_STRIPE::HasPaymentMethod(); 
		if($response == true){
			EcomSurance::view( 'email-templates/emailtemplates' );
		}else{
			EcomSurance::view( 'billing-portal' );
		}
	}  

	public static function display_page_emailtemplatesedit() {
		$response= EcomSurance_STRIPE::HasPaymentMethod(); 
		if($response == true){
			EcomSurance::view( 'email-templates/emailtemplatesedit' );
		}else{
			EcomSurance::view( 'billing-portal' );
		} 
	} 
}
